// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl02c3zOvfBhnK4nE0_vXrydGoe6p-Wac',
    appId: '1:323363797529:web:3e6b0a5b634b1e16d90888',
    messagingSenderId: '323363797529',
    projectId: 'timecapsule-9af15',
    authDomain: 'timecapsule-9af15.firebaseapp.com',
    storageBucket: 'timecapsule-9af15.appspot.com',
    measurementId: 'G-0R2CWC2MMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9qtwuu86cSJbLMR7tXflNcMB0h9rN8No',
    appId: '1:323363797529:android:f8d2446a3c452d4ad90888',
    messagingSenderId: '323363797529',
    projectId: 'timecapsule-9af15',
    storageBucket: 'timecapsule-9af15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPyWS0GquSDxFAmvMp-hS6iTnm6bRT2XE',
    appId: '1:323363797529:ios:b6b382d935006050d90888',
    messagingSenderId: '323363797529',
    projectId: 'timecapsule-9af15',
    storageBucket: 'timecapsule-9af15.appspot.com',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPyWS0GquSDxFAmvMp-hS6iTnm6bRT2XE',
    appId: '1:323363797529:ios:b6b382d935006050d90888',
    messagingSenderId: '323363797529',
    projectId: 'timecapsule-9af15',
    storageBucket: 'timecapsule-9af15.appspot.com',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl02c3zOvfBhnK4nE0_vXrydGoe6p-Wac',
    appId: '1:323363797529:web:5db5e9b66de7f9c9d90888',
    messagingSenderId: '323363797529',
    projectId: 'timecapsule-9af15',
    authDomain: 'timecapsule-9af15.firebaseapp.com',
    storageBucket: 'timecapsule-9af15.appspot.com',
    measurementId: 'G-JTF8X44K63',
  );
}
